# 服务配置
server:
 type: http
 port: 8003
 # 若不设port端口，则需要配置pin用于匹配
 # pin: 'code:sdaasbdjhasbnjdha'
 # 主机地址后期可使用域名更安全
 host: 127.0.0.1

# Redis
redis:
 # redis连接配置
 options:
  host: 127.0.0.1
  port: 6379
  # 用户名，默认无
  username: null
  # 密码，默认无密码
  password: null
  # 存到第一个数据库里，默认为0（第一个库），redis默认有16个库
  db: 0
 # redis连接池
 pool:
  # 最小连接数（初始化）
  minConnNum: 6
  # 最大连接数
  maxConnNum: 10
  # 最长等待时间（无空闲连接时等待时间）,毫秒数
  maxWaitTime: 2000
  # 连接最大引用次数
  maxUseTimes: 10

# common
common:
 # 表前缀，包括缓存表如redis的key和其他数据库表名
 # 表名使用大写字母+下划线命名法
 tablePrefix: KOA_
